repos:
  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
    - id: yapf
      name: "yapf"
      args: ['--parallel', '--in-place', '--style={based_on_style: google, column_limit: 120, indent_width: 4}']
